# Generated by Django 6.0.7 on 2026-07-14 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('OVERDUE', 'Overdue'), ('DONE_A', 'Done (Assignee)'), ('DONE_D', 'Done (Delegator)'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('acceptance_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], default='P3', max_length=2)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskPersonalLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=100)),
                ('color_code', models.CharField(default='#6B7280', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task_personal_labels',
            },
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_transcript', models.TextField()),
                ('language', models.CharField(blank=True, max_length=16, null=True)),
                ('duration_secs', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('audio_url', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'voice_recordings',
            },
        ),
    ]
