# Generated by Django 6.0.7 on 2026-07-14 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0002_initial'),
        ('tasks', '0001_initial'),
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_assigned', to='users.user'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_delegated', to='users.user'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subtasks', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='project_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='labels.projectlabel'),
        ),
        migrations.AddField(
            model_name='task',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='taskpersonallabel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_labels', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskpersonallabel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_labels', to='users.user'),
        ),
        migrations.AddField(
            model_name='voicerecording',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recording', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='voicerecording',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_recordings', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='idx_tasks_status'),
        ),
        migrations.AddConstraint(
            model_name='taskpersonallabel',
            constraint=models.UniqueConstraint(fields=('task', 'user', 'label'), name='uq_task_personal_label'),
        ),
    ]
