# Generated by Django 6.0.7 on 2026-07-18 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_remove_projectlabel_uq_project_label_tenant_name_and_more'),
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taskpersonallabel',
            name='uq_task_personal_label',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project_label',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignee_label_tasks', to='labels.projectlabel'),
        ),
        migrations.AddField(
            model_name='task',
            name='main_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_label_tasks', to='labels.projectlabel'),
        ),
        migrations.DeleteModel(
            name='TaskPersonalLabel',
        ),
    ]
