# Generated by Django 6.0.7 on 2026-07-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_remove_projectlabel_uq_project_label_tenant_name_and_more'),
        ('tasks', '0003_remove_taskpersonallabel_uq_task_personal_label_and_more'),
        ('tenants', '0002_initial'),
        ('users', '0002_user_last_login_at_user_last_logout_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            # Every list-view query in TaskRepository (list_assigned/list_delegated/
            # list_needs_attention/counts) filters on tenant_id + status together.
            index=models.Index(fields=['tenant', 'status'], name='idx_tasks_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            # Backs assignee-scoped lookups and the dashboard "my tasks" queries.
            index=models.Index(fields=['assignee'], name='idx_tasks_assignee'),
        ),
        migrations.AddIndex(
            model_name='task',
            # Backs SORT_ORDER's due_date sort and future "due this week"/overdue-scan queries.
            index=models.Index(fields=['due_date'], name='idx_tasks_due_date'),
        ),
        migrations.AddIndex(
            model_name='task',
            # Partial index: list views default to is_archived=False, which is the
            # overwhelming majority of day-to-day reads -- keeps the index small by
            # excluding DoneD/archived rows that are never queried this way.
            index=models.Index(condition=models.Q(('is_archived', False)), fields=['is_archived'], name='idx_tasks_not_archived'),
        ),
    ]
