# Generated by Django 6.0.7 on 2026-08-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_idx_tasks_tenant_status_task_idx_tasks_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='evidence_required',
            field=models.BooleanField(default=False),
        ),
    ]
