# Generated by Django 6.0.7 on 2026-08-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_evidence_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicerecording',
            name='carry_voice_recording',
            field=models.BooleanField(default=False),
        ),
    ]
