# Generated by Django 6.0.7 on 2026-08-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_voicerecording_carry_voice_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_today_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_tomorrow_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
