# Generated by Django 6.0.8 on 2026-08-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        # PlatformAdmin RBAC tier (ROADMAP.md Phase 15a). NOT NULL with a
        # default, so existing rows backfill to SUPER_ADMIN -- the only tier
        # that exists today. Read from the admin_token JWT by
        # HasPlatformAdminRole; see apps/platform_admin/tokens.py.
        migrations.AddField(
            model_name='platformadmin',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin')], default='SUPER_ADMIN', max_length=32),
        ),
    ]
