# Generated by Django 6.0.7 on 2026-07-14 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_url', models.CharField(max_length=512)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('PDF', 'PDF'), ('DOC', 'Document'), ('OTHER', 'Other')], max_length=10)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'evidence',
            },
        ),
    ]
