# Generated by Django 6.0.7 on 2026-07-14 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sticky_notes', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='promoted_to_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promoted_from_note', to='tasks.task'),
        ),
    ]
