# Generated by Django 6.0.7 on 2026-07-14 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sticky_notes', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sticky_notes', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='stickynote',
            index=models.Index(fields=['due_at'], name='idx_sticky_notes_due_at'),
        ),
    ]
