# Generated by Django 6.0.7 on 2026-08-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_notes', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='color_code',
            field=models.CharField(default='#FEF3C7', max_length=7),
        ),
    ]
