# Generated by Django 6.0.7 on 2026-08-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_notes', '0004_stickynote_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='reminder_fired',
            field=models.BooleanField(default=False),
        ),
    ]
