# Generated by Django 6.0.7 on 2026-07-14 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_headed', to='users.user'),
        ),
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('pk', models.CompositePrimaryKey('tenant', 'user', blank=True, editable=False, primary_key=True, serialize=False)),
                ('role_level', models.CharField(choices=[('TOP', 'Top'), ('MID', 'Mid'), ('EXECUTOR', 'Executor')], max_length=20)),
                ('role_label', models.CharField(blank=True, max_length=100, null=True)),
                ('can_broadcast', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='membership', to='users.user')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenants.department')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_reports', to='users.user')),
            ],
            options={
                'db_table': 'tenant_memberships',
            },
        ),
    ]
