# Generated by Django 6.0.7 on 2026-08-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='url_slug',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
