# Generated by Django 6.0.8 on 2026-08-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_url_slug'),
    ]

    operations = [
        # Tenant offboarding lifecycle (ROADMAP.md Phase 15e). NOT NULL + default,
        # so every existing tenant backfills to ACTIVE -- no behaviour change until
        # an operator PATCHes a tenant to SUSPENDED.
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=16),
        ),
        migrations.AddField(
            model_name='tenant',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
