# Generated by Django 6.0.7 on 2026-07-14 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('color_code', models.CharField(default='#6B7280', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_labels',
            },
        ),
    ]
