# Generated by Django 6.0.7 on 2026-07-14 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlabel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_labels_created', to='users.user'),
        ),
        migrations.AddField(
            model_name='projectlabel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_labels', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='projectlabel',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_project_label_tenant_name'),
        ),
    ]
