# Generated by Django 6.0.7 on 2026-07-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_initial'),
        ('tenants', '0002_initial'),
        ('users', '0002_user_last_login_at_user_last_logout_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectlabel',
            name='uq_project_label_tenant_name',
        ),
        migrations.AddConstraint(
            model_name='projectlabel',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='uq_project_label_created_by_name'),
        ),
    ]
