# Generated by Django 6.0.7 on 2026-07-14 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('preferred_lang', models.CharField(choices=[('EN', 'English'), ('HI', 'Hindi')], default='EN', max_length=2)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenants.tenant')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
