# Generated by Django 6.0.7 on 2026-07-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_REASSIGNED', 'Task Reassigned'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_PRIORITY_CHANGED', 'Task Priority Changed'), ('TASK_DUE_DATE_CHANGED', 'Task Due Date Changed'), ('TASK_LABEL_CHANGED', 'Task Label Changed'), ('TASK_ARCHIVED', 'Task Archived'), ('SUBTASK_CREATED', 'Subtask Created'), ('SUBTASK_UPDATED', 'Subtask Updated'), ('SUBTASK_DELETED', 'Subtask Deleted'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_DELETED', 'Document Deleted'), ('DOCUMENT_DOWNLOADED', 'Document Downloaded'), ('DOCUMENT_ACCESSED', 'Document Accessed'), ('BROADCAST_CREATED', 'Broadcast Created'), ('BROADCAST_UPDATED', 'Broadcast Updated'), ('BROADCAST_DELETED', 'Broadcast Deleted'), ('BROADCAST_PUBLISHED', 'Broadcast Published'), ('BROADCAST_ACKNOWLEDGED', 'Broadcast Acknowledged'), ('BROADCAST_VIEWED', 'Broadcast Viewed'), ('AUDIENCE_SCOPE_CREATED', 'Audience Scope Created'), ('AUDIENCE_SCOPE_MODIFIED', 'Audience Scope Modified'), ('AUDIENCE_SCOPE_ASSIGNMENT_CHANGED', 'Audience Scope Assignment Changed'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_PROFILE_UPDATED', 'User Profile Updated'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_PERMISSION_CHANGED', 'User Permission Changed'), ('TENANT_CREATED', 'Tenant Created'), ('MEMBER_ADDED', 'Member Added'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBERS_BULK_IMPORTED', 'Members Bulk Imported')], max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor_type',
            field=models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System'), ('PLATFORM_ADMIN', 'Platform Admin')], default='USER', max_length=14),
        ),
    ]
