# Generated by Django 6.0.7 on 2026-07-14 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_json', models.JSONField()),
                ('message_html', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('audience_role_level', models.CharField(blank=True, choices=[('TOP', 'Top'), ('MID', 'Mid'), ('EXECUTOR', 'Executor')], max_length=20, null=True)),
                ('requires_acknowledgement', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, max_length=512, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'broadcast_notices',
            },
        ),
    ]
