# Generated by Django 6.0.7 on 2026-07-14 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broadcasts', '0001_initial'),
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotice',
            name='audience_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='broadcasts', to='tenants.department'),
        ),
        migrations.AddField(
            model_name='broadcastnotice',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcasts_sent', to='users.user'),
        ),
        migrations.AddField(
            model_name='broadcastnotice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcasts', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='broadcastnotice',
            index=models.Index(fields=['expires_at'], name='idx_broadcast_expires_at'),
        ),
        migrations.CreateModel(
            name='BroadcastAcknowledgement',
            fields=[
                ('pk', models.CompositePrimaryKey('broadcast', 'user', blank=True, editable=False, primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='broadcasts.broadcastnotice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcast_acknowledgements', to='users.user')),
            ],
            options={
                'db_table': 'broadcast_acknowledgements',
            },
        ),
    ]
