# Generated by Django 6.0.7 on 2026-07-18 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastacknowledgement',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='broadcasts.broadcastnotice'),
        ),
    ]
