# Generated by Django 6.0.7 on 2026-07-23 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0003_alter_broadcastacknowledgement_broadcast'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastnotice',
            name='audience_dept',
        ),
        migrations.CreateModel(
            name='BroadcastNoticeAudienceDept',
            fields=[
                ('pk', models.CompositePrimaryKey('broadcast', 'department', blank=True, editable=False, primary_key=True, serialize=False)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_depts', to='broadcasts.broadcastnotice')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcast_audiences', to='tenants.department')),
            ],
            options={
                'db_table': 'broadcast_notice_audience_depts',
            },
        ),
    ]
