# Generated by Django 6.0.7 on 2026-08-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0004_remove_broadcastnotice_audience_dept_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastnotice',
            name='audience_role_level',
        ),
        migrations.CreateModel(
            name='BroadcastNoticeAudienceRoleLevel',
            fields=[
                ('pk', models.CompositePrimaryKey('broadcast', 'role_level', blank=True, editable=False, primary_key=True, serialize=False)),
                ('role_level', models.CharField(choices=[('TOP', 'Top'), ('MID', 'Mid'), ('EXECUTOR', 'Executor')], max_length=20)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_role_levels', to='broadcasts.broadcastnotice')),
            ],
            options={
                'db_table': 'broadcast_notice_audience_role_levels',
            },
        ),
    ]
