# Generated by Django 6.0.7 on 2026-07-14 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_ACCEPTED', 'Task Accepted'), ('TASK_REASSIGNED', 'Task Reassigned'), ('TASK_EDITED', 'Task Edited'), ('TASK_COMMENTED', 'Task Commented'), ('TASK_DONE_A', 'Task Done (Assignee)'), ('TASK_DONE_D', 'Task Done (Delegator)'), ('TASK_CANCELLED', 'Task Cancelled'), ('TASK_REMINDER', 'Task Reminder'), ('TASK_DUE_TODAY', 'Task Due Today'), ('TASK_DUE_TOMORROW', 'Task Due Tomorrow'), ('TASK_OVERDUE', 'Task Overdue'), ('SUBTASK_CREATED', 'Subtask Created'), ('SUBTASK_EDITED', 'Subtask Edited'), ('SUBTASK_DONE_A', 'Subtask Done (Assignee)'), ('SUBTASK_DONE_D', 'Subtask Done (Delegator)'), ('BROADCAST_POSTED', 'Broadcast Posted'), ('REMINDER_FIRED', 'Reminder Fired'), ('AI_NUDGE_FOLLOWUP', 'AI Nudge - Follow-up'), ('AI_NUDGE_DUE_PROXIMITY', 'AI Nudge - Due Proximity')], max_length=30)),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=500)),
                ('actor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_title', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_context', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='NudgeSkipCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('nudge_kind', models.CharField(max_length=64)),
                ('skip_count', models.PositiveIntegerField(default=0)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nudge_skip_counters',
            },
        ),
    ]
