# Generated by Django 6.0.7 on 2026-07-14 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications_received', to='users.user'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='nudgeskipcounter',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nudge_skip_counters', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='nudgeskipcounter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nudge_skip_counters', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='idx_notif_recipient_read'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['entity_type', 'entity_id'], name='idx_notif_entity'),
        ),
        migrations.AddConstraint(
            model_name='nudgeskipcounter',
            constraint=models.UniqueConstraint(fields=('user', 'entity_type', 'entity_id', 'nudge_kind'), name='uq_nudge_skip_counter'),
        ),
    ]
