# Generated by Django 6.0.7 on 2026-07-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nudgeskipcounter',
            name='uq_nudge_skip_counter',
        ),
        migrations.AddField(
            model_name='nudgeskipcounter',
            name='last_shown_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_ACCEPTED', 'Task Accepted'), ('TASK_REASSIGNED', 'Task Reassigned'), ('TASK_EDITED', 'Task Edited'), ('TASK_COMMENTED', 'Task Commented'), ('TASK_DONE_A', 'Task Done (Assignee)'), ('TASK_DONE_D', 'Task Done (Delegator)'), ('TASK_CANCELLED', 'Task Cancelled'), ('TASK_REMINDER', 'Task Reminder'), ('TASK_DUE_TODAY', 'Task Due Today'), ('TASK_DUE_TOMORROW', 'Task Due Tomorrow'), ('TASK_OVERDUE', 'Task Overdue'), ('SUBTASK_CREATED', 'Subtask Created'), ('SUBTASK_EDITED', 'Subtask Edited'), ('SUBTASK_DONE_A', 'Subtask Done (Assignee)'), ('SUBTASK_DONE_D', 'Subtask Done (Delegator)'), ('BROADCAST_POSTED', 'Broadcast Posted'), ('EVIDENCE_ATTACHED', 'Evidence Attached'), ('REMINDER_FIRED', 'Reminder Fired'), ('AI_NUDGE_FOLLOWUP', 'AI Nudge - Follow-up'), ('AI_NUDGE_DUE_PROXIMITY', 'AI Nudge - Due Proximity')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='nudgeskipcounter',
            constraint=models.UniqueConstraint(fields=('entity_type', 'entity_id', 'nudge_kind'), name='uq_nudge_skip_counter'),
        ),
        migrations.RemoveField(
            model_name='nudgeskipcounter',
            name='user',
        ),
    ]
